version: '3.8'

services:
  db:
    image: postgres:15
    container_name: patient-postgres
    environment:
      POSTGRES_USER: patientuser
      POSTGRES_PASSWORD: secretpass
      POSTGRES_DB: patientdb
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: patient-management-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/patientdb
      SPRING_DATASOURCE_USERNAME: patientuser
      SPRING_DATASOURCE_PASSWORD: secretpass
    # Uncomment below if you want to auto-restart app on crash
    # restart: always

volumes:
  db-data:
